import type { Conversation, ConversationDetail, Message } from './message.api';

// Mock conversations data
export const mockConversations: Conversation[] = [
  {
    id: 1,
    userId: 101,
    userName: 'Nguyễn Văn An',
    userEmail: 'nguyenvanan@gmail.com',
    userAvatar: 'https://i.pravatar.cc/150?img=1',
    subject: 'Hỏi về sản phẩm',
    status: 'open',
    lastMessageAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 minutes ago
    lastMessageContent: 'Cảm ơn admin đã hỗ trợ!',
    unreadCount: 2,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    userId: 102,
    userName: 'Trần Thị Bình',
    userEmail: 'tranthibinh@gmail.com',
    userAvatar: 'https://i.pravatar.cc/150?img=5',
    subject: 'Vấn đề giao hàng',
    status: 'open',
    lastMessageAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 minutes ago
    lastMessageContent: 'Đơn hàng của tôi đến khi nào vậy ạ?',
    unreadCount: 1,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    userId: 103,
    userName: 'Lê Văn Cường',
    userEmail: 'levancuong@gmail.com',
    userAvatar: 'https://i.pravatar.cc/150?img=12',
    subject: 'Đổi trả sản phẩm',
    status: 'closed',
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    lastMessageContent: 'Vâng, em cảm ơn admin ạ!',
    unreadCount: 0,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    userId: 104,
    userName: 'Phạm Thị Dung',
    userEmail: 'phamthidung@gmail.com',
    userAvatar: 'https://i.pravatar.cc/150?img=9',
    subject: 'Hỏi về khuyến mãi',
    status: 'open',
    lastMessageAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), // 4 hours ago
    lastMessageContent: 'Cho em hỏi chương trình khuyến mãi còn không ạ?',
    unreadCount: 3,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    userId: 105,
    userName: 'Hoàng Văn Em',
    userEmail: 'hoangvanem@gmail.com',
    userAvatar: 'https://i.pravatar.cc/150?img=15',
    subject: 'Thanh toán thất bại',
    status: 'open',
    lastMessageAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    lastMessageContent: 'Em thanh toán bị lỗi, giúp em với ạ!',
    unreadCount: 1,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 6,
    userId: 106,
    userName: 'Võ Thị Giang',
    userEmail: 'vothigiang@gmail.com',
    userAvatar: 'https://i.pravatar.cc/150?img=20',
    subject: 'Hỏi về size sản phẩm',
    status: 'archived',
    lastMessageAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days ago
    lastMessageContent: 'Ok em đã hiểu rồi, cảm ơn shop!',
    unreadCount: 0,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 7,
    userId: 104,
    userName: 'Phạm Thị Dung',
    userEmail: 'phamthidung@gmail.com',
    userAvatar: 'https://i.pravatar.cc/150?img=9',
    subject: 'Hỏi về khuyến mãi',
    status: 'open',
    lastMessageAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), // 4 hours ago
    lastMessageContent: 'Cho em hỏi chương trình khuyến mãi còn không ạ?',
    unreadCount: 3,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 8,
    userId: 105,
    userName: 'Hoàng Văn Em',
    userEmail: 'hoangvanem@gmail.com',
    userAvatar: 'https://i.pravatar.cc/150?img=15',
    subject: 'Thanh toán thất bại',
    status: 'open',
    lastMessageAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    lastMessageContent: 'Em thanh toán bị lỗi, giúp em với ạ!',
    unreadCount: 1,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 9,
    userId: 106,
    userName: 'Võ Thị Giang',
    userEmail: 'vothigiang@gmail.com',
    userAvatar: 'https://i.pravatar.cc/150?img=20',
    subject: 'Hỏi về size sản phẩm',
    status: 'archived',
    lastMessageAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days ago
    lastMessageContent: 'Ok em đã hiểu rồi, cảm ơn shop!',
    unreadCount: 0,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock messages for each conversation
export const mockMessages: Record<number, Message[]> = {
  1: [
    {
      id: 1,
      conversationId: 1,
      senderId: 101,
      senderName: 'Nguyễn Văn An',
      senderAvatar: 'https://i.pravatar.cc/150?img=1',
      content: 'Xin chào, cho mình hỏi sản phẩm áo thun basic có size XL không ạ?',
      isAdminReply: false,
      isRead: true,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 2,
      conversationId: 1,
      senderId: 1,
      senderName: 'Admin',
      content:
        'Chào bạn! Hiện tại shop có size XL cho sản phẩm áo thun basic bạn nhé. Bạn có thể đặt hàng ngay.',
      isAdminReply: true,
      isRead: true,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
    },
    {
      id: 3,
      conversationId: 1,
      senderId: 101,
      senderName: 'Nguyễn Văn An',
      senderAvatar: 'https://i.pravatar.cc/150?img=1',
      content: 'Vậy mình đặt 2 cái được không? Có giảm giá không ạ?',
      isAdminReply: false,
      isRead: true,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
    },
    {
      id: 4,
      conversationId: 1,
      senderId: 1,
      senderName: 'Admin',
      content:
        'Dạ được ạ! Hiện tại shop đang có chương trình mua 2 giảm 10%. Bạn đặt hàng là được áp dụng luôn nhé!',
      isAdminReply: true,
      isRead: true,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
    },
    {
      id: 5,
      conversationId: 1,
      senderId: 101,
      senderName: 'Nguyễn Văn An',
      senderAvatar: 'https://i.pravatar.cc/150?img=1',
      content: 'Cảm ơn admin đã hỗ trợ!',
      isAdminReply: false,
      isRead: false,
      createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
  ],
  2: [
    {
      id: 6,
      conversationId: 2,
      senderId: 102,
      senderName: 'Trần Thị Bình',
      senderAvatar: 'https://i.pravatar.cc/150?img=5',
      content:
        'Cho em hỏi đơn hàng #12345 của em đến khi nào vậy ạ? Em đặt từ 3 ngày trước rồi mà chưa thấy giao.',
      isAdminReply: false,
      isRead: true,
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 7,
      conversationId: 2,
      senderId: 1,
      senderName: 'Admin',
      content: 'Chào bạn! Để admin kiểm tra đơn hàng cho bạn nhé. Bạn vui lòng đợi trong giây lát.',
      isAdminReply: true,
      isRead: true,
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
    },
    {
      id: 8,
      conversationId: 2,
      senderId: 1,
      senderName: 'Admin',
      content:
        'Admin đã kiểm tra rồi ạ. Đơn hàng của bạn hiện đang ở bưu cục gần nhà bạn. Dự kiến sẽ giao trong hôm nay hoặc sáng mai nhé!',
      isAdminReply: true,
      isRead: true,
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
    },
    {
      id: 9,
      conversationId: 2,
      senderId: 102,
      senderName: 'Trần Thị Bình',
      senderAvatar: 'https://i.pravatar.cc/150?img=5',
      content: 'Đơn hàng của tôi đến khi nào vậy ạ?',
      isAdminReply: false,
      isRead: false,
      createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
  ],
  3: [
    {
      id: 10,
      conversationId: 3,
      senderId: 103,
      senderName: 'Lê Văn Cường',
      senderAvatar: 'https://i.pravatar.cc/150?img=12',
      content: 'Em muốn đổi sản phẩm vì size không vừa. Shop có hỗ trợ đổi không ạ?',
      isAdminReply: false,
      isRead: true,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 11,
      conversationId: 3,
      senderId: 1,
      senderName: 'Admin',
      content:
        'Dạ shop có hỗ trợ đổi size trong vòng 7 ngày ạ. Bạn vui lòng gửi lại sản phẩm về địa chỉ của shop, shop sẽ gửi size mới cho bạn nhé!',
      isAdminReply: true,
      isRead: true,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
    },
    {
      id: 12,
      conversationId: 3,
      senderId: 103,
      senderName: 'Lê Văn Cường',
      senderAvatar: 'https://i.pravatar.cc/150?img=12',
      content: 'Vâng, em cảm ơn admin ạ!',
      isAdminReply: false,
      isRead: true,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  4: [
    {
      id: 13,
      conversationId: 4,
      senderId: 104,
      senderName: 'Phạm Thị Dung',
      senderAvatar: 'https://i.pravatar.cc/150?img=9',
      content: 'Cho em hỏi chương trình khuyến mãi Black Friday còn không ạ?',
      isAdminReply: false,
      isRead: false,
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    },
  ],
  5: [
    {
      id: 14,
      conversationId: 5,
      senderId: 105,
      senderName: 'Hoàng Văn Em',
      senderAvatar: 'https://i.pravatar.cc/150?img=15',
      content: 'Em thanh toán bằng VNPay bị lỗi, nhưng tiền đã bị trừ. Giúp em với ạ!',
      isAdminReply: false,
      isRead: false,
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  6: [
    {
      id: 15,
      conversationId: 6,
      senderId: 106,
      senderName: 'Võ Thị Giang',
      senderAvatar: 'https://i.pravatar.cc/150?img=20',
      content: 'Cho em hỏi áo size M tương đương với size nào của Việt Nam vậy ạ?',
      isAdminReply: false,
      isRead: true,
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 16,
      conversationId: 6,
      senderId: 1,
      senderName: 'Admin',
      content:
        'Size M của shop tương đương với size 50-55kg, cao 1m55-1m65 ạ. Bạn tham khảo bảng size chi tiết ở trang sản phẩm nhé!',
      isAdminReply: true,
      isRead: true,
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
    },
    {
      id: 17,
      conversationId: 6,
      senderId: 106,
      senderName: 'Võ Thị Giang',
      senderAvatar: 'https://i.pravatar.cc/150?img=20',
      content: 'Ok em đã hiểu rồi, cảm ơn shop!',
      isAdminReply: false,
      isRead: true,
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

// Helper function to get conversation details with messages
export const getMockConversationDetail = (id: number): ConversationDetail | null => {
  const conversation = mockConversations.find((c) => c.id === id);
  if (!conversation) return null;

  return {
    ...conversation,
    messages: mockMessages[id] || [],
  };
};
